// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeEa2tTvV_opygbGVHpMABgVwaGa_CBrE',
    appId: '1:21711608226:web:3431fbaadb9f795bdefafb',
    messagingSenderId: '21711608226',
    projectId: 'smartchat-b9dcc',
    authDomain: 'smartchat-b9dcc.firebaseapp.com',
    storageBucket: 'smartchat-b9dcc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbV6ucV9WqkrDMs0otQP7ZhuKA8IaM38c',
    appId: '1:21711608226:android:56c4c7985caede50defafb',
    messagingSenderId: '21711608226',
    projectId: 'smartchat-b9dcc',
    storageBucket: 'smartchat-b9dcc.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeEa2tTvV_opygbGVHpMABgVwaGa_CBrE',
    appId: '1:21711608226:web:32729dafeb7b4f35defafb',
    messagingSenderId: '21711608226',
    projectId: 'smartchat-b9dcc',
    authDomain: 'smartchat-b9dcc.firebaseapp.com',
    storageBucket: 'smartchat-b9dcc.firebasestorage.app',
  );

}